### PR TITLE
fix(react-props): Supports React nodes as content

### LINKED ISSUE #64: Implement support for passing React elements as properties
To further customize content, allow consumers to pass React nodes to be applied as children in step layout. For example,

`
step: {
  bodyHeader: ReactNode | string;
}
`

### PR DESCRIPTION
**Pull request by froehlichcr**
# Story Reference

This fixes #64

## Summary

__REPLACE__

## Author Checklist

I have added/updated:

- [ x] Release notes (title of this PR)

## Version Bump

- [x] Patch (bug fix - backwards compatible)

### CODE REVIEW

File: src/components/lib/Pages.tsx [hunk 1]
```diff
@@ -59,11 +60,9 @@ export abstract class Pages {
           {result.label}:{'  '}
           <b>{result.name}</b>
         </span>
-        <div
+        <Div
```
Comment (TomNUSDS) [inline src/components/lib/Pages.tsx:63]: Humm... relying on Case seems pretty subtle. I guess it's kind of a React-ism.

File: src/stories/flows/eligibility/data/pages.flow.tsx [hunk 2]
```diff
@@ -16,26 +16,25 @@ export const pages: IPages = {
...
-<p/>
-The information you shared today tells us about your current situation. In the future, you may become eligible for other benefits as you age or things in your life change.`,
     bodyHeader:    'Benefits you may be eligible for',
     bodySubHeader: "Here's what you may be eligible for and why",
-    id:            PAGE_TYPE.RESULTS,
-    info:          'Each benefit we provide has an official name. You may see these names in other materials or hear our employees use them on the phone and in our offices.',
-    section:       { id: PAGE_TYPE.RESULTS },
-    title:         'You may be eligible for benefits.',
-    type:          PAGE_TYPE.RESULTS,
+    children:      (<>This gives you an idea of what you may be eligible for, but we can{"'"}t guarantee you{"'"}ll get these benefits. We{"'"}ll analyze more details during the application process to provide a definite answer.
```
Comment (TomNUSDS) [inline src/stories/flows/eligibility/data/pages.flow.tsx:30]: `{"'"}` is really ugly. Also, it will also be tricky for content editors once it gets moved into drupal and content editors try to work with it.
Maybe put the whole sentence into `{"` like:
`{"This gives you an idea of what you may be eligible for, but we can't guarantee you'll get these benefits. We'll analyze more details during the application process to provide a definite answer."}`?
Not a big deal, just an interesting formatting/escaping challenge.
