### PR TITLE
fix(data-model): uses reference types

### LINKED ISSUE #51: Update data model to support references
To support better editing, relationships should be defined by reference instead of by id.

Use `Partial` objects to relate questions/answers/responses/requirements.

### PR DESCRIPTION
**Pull request by froehlichcr**
# Story Reference

This fixes #51

## Summary

- Separates interfaces into individual files
- Remove object maps and replace with partial reference objects
- Rename `requirements.answers.answers` > `requirements.responses.answers`
- Refactored flow example data

## Author Checklist

I have added/updated:

- [x] Tests
- [x] Documentation
- [x] Release notes (title of this PR)

## Version Bump

- [x] Patch (bug fix - backwards compatible)

### CODE REVIEW

File: src/components/lib/Pages.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ export abstract class Pages {
         reason += `You are ${props.form.age?.years} years `;
         reason += `and ${props.form.age?.months} months old. `;
       }
-      Object.keys(result.match.answers).forEach((id) => {
+      Object.keys(result.match.responses).forEach((id) => {
```
Comment (TomNUSDS) [inline src/components/lib/Pages.tsx:34]: Naming is hard. `responses` makes me thing of network responses not answers. But this is just my opinion... feel free to ignore it.

File: src/stories/flows/complex/data/sections.flow.ts [hunk 2]
```diff
@@ -1,25 +1,24 @@
...
   },
   {
     id:           'a0_work',
     name:         'Work',
     requirements: [
       {
-        answers: {
-          A: [0], // Only for adults
-        },
+        explanation: '18 or older',
```
Comment (TomNUSDS) [inline src/stories/flows/complex/data/sections.flow.ts:15]: like `explanation` addition

**Review by TomNUSDS — APPROVED** [review]
lgtm
